### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by kuzmichevdima** [Sergmih/python-review#20]
запускаю так:

python3 train.py --input-dir ../gen_tests --model model

Traceback (most recent call last):
  File "train.py", line 85, in <module>
    update_model_dict(f, model_dict)
  File "train.py", line 57, in update_model_dict
    parser.parse_args().lc, model_dict)
  File "train.py", line 29, in create_model
    return words[len(words) - 1]
IndexError: list index out of range

**Comment by kuzmichevdima** [comment]
python3 train.py --input-dir ../gen_tests/ --model model

Traceback (most recent call last):
  File "train.py", line 88, in <module>
    update_model_dict(f, model_dict)
  File "train.py", line 58, in update_model_dict
    new_string += ' ' + current_string
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
